"""
Django settings for lumenlock project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (development only)
# Requires explicit opt-in via DJANGO_LOAD_DOTENV=true to prevent production misconfiguration
# This prevents accidental .env override if .env is present in production containers
# For development: set DJANGO_LOAD_DOTENV=true in your environment or shell
use_dotenv = os.getenv('DJANGO_LOAD_DOTENV', '').lower() in ('true', '1', 'yes')
if use_dotenv:
    env_file = BASE_DIR / '.env'
    if env_file.exists():
        load_dotenv(env_file)
elif (BASE_DIR / '.env').exists() and not os.getenv('SECRET_KEY'):
    # .env exists but DJANGO_LOAD_DOTENV not set - auto-load for convenience
    # This allows development to work without setting env vars
    # Production should always set SECRET_KEY explicitly, bypassing this
    load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Parse DEBUG with case-insensitive boolean handling (supports: True/true/TRUE/1/yes/YES)
# Defaults to False for security - set DEBUG=True in .env for local development
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    # Provide fallback for development/testing when DEBUG is not explicitly False
    # This allows manage.py commands to work in fresh dev/test/CI environments
    if DEBUG or os.getenv('DEBUG') is None:
        # Safe fallback for local dev/testing
        # This key is public and should NEVER be used in production
        SECRET_KEY = 'django-insecure-dev-key-for-local-testing-only-change-in-production'
    else:
        # In production (DEBUG explicitly set to False), require SECRET_KEY
        raise ValueError(
            "SECRET_KEY environment variable is required in production. "
            "Set it in your environment (not .env file)."
        )

# ALLOWED_HOSTS configuration with production safety
# Strip whitespace from each host to handle "example.com, www.example.com" format correctly
ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '').split(',') if host.strip()] if os.getenv('ALLOWED_HOSTS') else []
if not DEBUG and not ALLOWED_HOSTS:
    raise ValueError("ALLOWED_HOSTS must be set in production. Set it in your .env file (comma-separated list).")

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "allauth_ui",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'wallet',
    "widget_tweaks",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'lumenlock.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'lumenlock.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'dashboard'

# Django Allauth settings
# For development: disable email verification and use console backend
# For production: configure proper SMTP settings and enable verification
if DEBUG:
    ACCOUNT_EMAIL_VERIFICATION = 'none'
    ACCOUNT_EMAIL_REQUIRED = False
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Production: 'optional' allows access but encourages verification
    # For stricter security, consider changing to 'mandatory' to require
    # email verification before wallet access. This is a policy decision.
    ACCOUNT_EMAIL_VERIFICATION = 'optional'
    ACCOUNT_EMAIL_REQUIRED = True

# Stellar Network Configuration
STELLAR_HORIZON_URL = os.getenv('STELLAR_HORIZON_URL', 'https://horizon-testnet.stellar.org')
STELLAR_FRIENDBOT_URL = os.getenv('STELLAR_FRIENDBOT_URL', 'https://friendbot.stellar.org')
# Enable friendbot for testnet only (use network passphrase for reliable detection)
STELLAR_USE_FRIENDBOT = os.getenv('STELLAR_USE_FRIENDBOT', '').lower() in ('true', '1', 'yes')

# Derive network passphrase from Horizon URL if not explicitly set
# This prevents silent mismatches between mainnet Horizon and testnet passphrase
if 'STELLAR_NETWORK_PASSPHRASE' in os.environ:
    STELLAR_NETWORK_PASSPHRASE = os.getenv('STELLAR_NETWORK_PASSPHRASE')
else:
    # Extract hostname from URL for strict matching
    from urllib.parse import urlparse
    horizon_hostname = urlparse(STELLAR_HORIZON_URL).hostname or ''

    # Map known official Horizon hostnames to their network passphrases
    # Use exact hostname matching to avoid misclassification
    if horizon_hostname == 'horizon-testnet.stellar.org':
        STELLAR_NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015'
    elif horizon_hostname == 'horizon.stellar.org':
        STELLAR_NETWORK_PASSPHRASE = 'Public Global Stellar Network ; September 2015'
        # Warn if using mainnet without explicit configuration
        if DEBUG:
            import sys
            print(
                "WARNING: Auto-detected mainnet from Horizon URL. "
                "Set STELLAR_NETWORK_PASSPHRASE explicitly for production.",
                file=sys.stderr
            )
    else:
        # Unknown Horizon URL - require explicit passphrase
        raise ValueError(
            f"Cannot determine network passphrase from Horizon URL: {STELLAR_HORIZON_URL} (hostname: {horizon_hostname}). "
            "Please set STELLAR_NETWORK_PASSPHRASE explicitly in your .env file."
        )

# Auto-enable friendbot for testnet if not explicitly configured
if not os.getenv('STELLAR_USE_FRIENDBOT'):
    STELLAR_USE_FRIENDBOT = (STELLAR_NETWORK_PASSPHRASE == 'Test SDF Network ; September 2015')